In [8]:
import pandas as pd

#Adjust the path to where you have saved the data
df = pd.read_csv("data_text.csv")

In [9]:
df.head(20)

,PUF_ID,sample,fed_poverty,fwb_score,fwb1_handle_expense,fwb2_secure_future,fwb3_things_i_want,fwb4_enjoy_life,fwb5_just_getting_by,fwb6_worried_savings,...,age_category,generation,education,ethnicity,gender,household_size,household_income,marital_status,MSA_status,final_weight
0,10350,Age 62+ oversample,200%+ FPL,55,Somewhat,Somewhat,Somewhat,Somewhat,Very little,Somewhat,...,75+,Pre-Boomer,Bachelors degree,"White, Non-Hispanic",Male,1,"$75,000 to $99,999",Divorced/Separated,Metro,0.367292
1,7740,General population,200%+ FPL,51,Very little,Very little,Somewhat,Somewhat,Somewhat,Very well,...,35-44,Gen X,High school degree/GED,"White, Non-Hispanic",Male,2,"$60,000 to $74,999",Divorced/Separated,Metro,1.327561
2,13699,General population,200%+ FPL,49,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,...,35-44,Gen X,Some college/Associate,"Black, Non-Hispanic",Male,3,"$60,000 to $74,999",Divorced/Separated,Metro,0.835156
3,7267,General population,200%+ FPL,49,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,...,35-44,Gen X,High school degree/GED,"White, Non-Hispanic",Male,1,"$100,000 to $149,999",Divorced/Separated,Metro,1.410871
4,7375,General population,200%+ FPL,49,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,Somewhat,...,25-34,Millennial,High school degree/GED,"Other, Non-Hispanic",Male,5+,"$75,000 to $99,999",Married,Metro,4.260668
5,10910,General population,200%+ FPL,67,Completely,Not at all,Not at all,Not at all,Not at all,Not at all,...,25-34,Millennial,Bachelors degree,"White, Non-Hispanic",Male,2,"$75,000 to $99,999",Married,Metro,0.760061
6,11079,General population,200%+ FPL,51,Not at all,Somewhat,Very little,Somewhat,Somewhat,Somewhat,...,35-44,Gen X,Bachelors degree,Hispanic,Female,5+,"$75,000 to $99,999",Married,Metro,1.370522
7,7741,General population,200%+ FPL,47,Not at all,Very little,Very well,Somewhat,Somewhat,Somewhat,...,25-34,Millennial,Less than high school,"White, Non-Hispanic",Female,3,"$40,000 to $49,999",Never married,Metro,1.193365
8,8303,General population,200%+ FPL,43,Very well,Completely,Very little,Completely,Completely,Very little,...,35-44,Gen X,Less than high school,"Other, Non-Hispanic",Female,4,"$75,000 to $99,999",Married,Metro,2.497838
9,9688,General population,200%+ FPL,58,Somewhat,Somewhat,Very little,Somewhat,Somewhat,Somewhat,...,45-54,Gen X,High school degree/GED,"White, Non-Hispanic",Male,3,"$100,000 to $149,999",Married,Metro,1.266602
10,13180,General population,200%+ FPL,78,Completely,Completely,Not at all,Completely,Completely,Not at all,...,18-24,Millennial,Some college/Associate,"White, Non-Hispanic",Male,5+,"$60,000 to $74,999",Married,Metro,0.937912
11,10127,General population,200%+ FPL,62,Very well,Somewhat,Very little,Completely,Very little,Very little,...,62-69,Boomer,Bachelors degree,"White, Non-Hispanic",Female,2,"$100,000 to $149,999",Married,Non-Metro,0.745163
12,7852,General population,100%-199% FPL,50,Somewhat,Very well,Somewhat,Somewhat,Very well,Somewhat,...,18-24,Millennial,Some college/Associate,"White, Non-Hispanic",Female,4,"$30,000 to $39,999",Never married,Metro,1.292576
13,7376,General population,200%+ FPL,40,Very little,Very little,Very well,Very little,Very well,Very well,...,25-34,Millennial,Bachelors degree,"White, Non-Hispanic",Male,3,"$150,000 or more",Never married,Metro,1.140934
14,8304,General population,200%+ FPL,61,Completely,Very well,Very little,Completely,Very little,Somewhat,...,25-34,Millennial,Graduate/professional degree,"White, Non-Hispanic",Male,3,"$150,000 or more",Married,Metro,0.810600
15,11726,General population,<100% FPL,69,Very well,Very well,Not at all,Very well,Not at all,Not at all,...,25-34,Millennial,Less than high school,Hispanic,Male,5+,"$20,000 to $29,999",Living with partner,Metro,4.283985
16,11221,General population,<100% FPL,37,Not at all,Not at all,Very well,Not at all,Completely,Very well,...,18-24,Millennial,High school degree/GED,"White, Non-Hispanic",Male,5+,"Less than $20,000",Never married,Metro,1.025192
17,8121,General population,200%+ FPL,52,Somewhat,Somewhat,Very little,Somewhat,Somewhat,Somewhat,...,18-24,Millennial,Some college/Associate,"White, Non-Hispanic",Female,2,"$30,000 to $39,999",Married,Metro,1.045181
18,8122,General population,200%+ FPL,69,Very well,Very well,Somewhat,Very well,Not at all,Somewhat,...,70-74,Pre-Boomer,Graduate/professional degree,"White, Non-Hispanic",Male,2,"$150,000 or more",Married,Metro,0.495053
19,12990,Age 62+ oversample,100%-199% FPL,67,Very little,Somewhat,Not at all,Somewhat,Somewhat,Not at all,...,62-69,Boomer,High school degree/GED,"Black, Non-Hispanic",Female,1,"$20,000 to $29,999",Divorced/Separated,Metro,0.866999

In [3]:
#Map values
df = df.replace({"sample":{
  1: "General population",
  2: "Age 62+ oversample",
  3: "Race/ethnicity and poverty oversample"
},
"fpl":{
  1: "<100% FPL",
  2: "100%-199% FPL",
  3: "200%+ FPL"
},
"FWBscore":{
  -4: "Response not written to database",
  -1: "Refused"
},
"FWB1_1":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Not at all",
  2: "Very little",
  3: "Somewhat",
  4: "Very well",
  5: "Completely"
},
"FWB1_2":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Not at all",
  2: "Very little",
  3: "Somewhat",
  4: "Very well",
  5: "Completely"
},
"FWB1_3":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Not at all",
  2: "Very little",
  3: "Somewhat",
  4: "Very well",
  5: "Completely"
},
"FWB1_4":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Not at all",
  2: "Very little",
  3: "Somewhat",
  4: "Very well",
  5: "Completely"
},
"FWB1_5":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Not at all",
  2: "Very little",
  3: "Somewhat",
  4: "Very well",
  5: "Completely"
},
"FWB1_6":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Not at all",
  2: "Very little",
  3: "Somewhat",
  4: "Very well",
  5: "Completely"
},
"FWB2_1":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Never",
  2: "Rarely",
  3: "Sometimes",
  4: "Often",
  5: "Always"
},
"FWB2_2":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Never",
  2: "Rarely",
  3: "Sometimes",
  4: "Often",
  5: "Always"
},
"FWB2_3":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Never",
  2: "Rarely",
  3: "Sometimes",
  4: "Often",
  5: "Always"
},
"FWB2_4":{
  -4: "Response not written to database",
  -1: "Refused",
  1: "Never",
  2: "Rarely",
  3: "Sometimes",
  4: "Often",
  5: "Always"
},
"FSscore":{
  -1: "Refused"
},
"HOUSING":{
  -1: "Refused",
  1: "I own my home",
  2: "I rent",
  3: "I do not currently own or rent"
},
"HOUSERANGES":{
  -1: "Refused",
  1: "Less than $300",
  2: "$300-499",
  3: "$500-749",
  4: "$750-999",
  5: "$1,000-1,499",
  6: "$1,500-1,999",
  7: "$2,000 or more",
  98: "I dont know",
  99: "Prefer not to say"
},
"SAVINGSRANGES":{
  -1: "Refused",
  1: "0",
  2: "$1-99",
  3: "$100-999",
  4: "$1,000-4,999",
  5: "$5,000-19,999",
  6: "$20,000-74,999",
  7: "$75,000 or more",
  98: "I dont know",
  99: "Prefer not to say"
},
"PRODHAVE_1":{
  0: "No",
  1: "Yes"
},
"PRODHAVE_3":{
  0: "No",
  1: "Yes"
},
"PRODHAVE_4":{
  0: "No",
  1: "Yes"
},
"PRODHAVE_5":{
  0: "No",
  1: "Yes"
},
"PRODUSE_1":{
  0: "No",
  1: "Yes"
},
"PRODUSE_2":{
  0: "No",
  1: "Yes"
},
"PRODUSE_5":{
  0: "No",
  1: "Yes"
},
"CONSPROTECT1":{
  -1: "Refused",
  1: "Never",
  2: "Rarely",
  3: "Sometimes",
  4: "Often"
},
"MATHARDSHIP_1":{
  -1: "Refused",
  1: "Never",
  2: "Sometimes",
  3: "Often"
},
"MATHARDSHIP_2":{
  -1: "Refused",
  1: "Never",
  2: "Sometimes",
  3: "Often"
},
"MATHARDSHIP_3":{
  -1: "Refused",
  1: "Never",
  2: "Sometimes",
  3: "Often"
},
"MATHARDSHIP_4":{
  -1: "Refused",
  1: "Never",
  2: "Sometimes",
  3: "Often"
},
"MATHARDSHIP_5":{
  -1: "Refused",
  1: "Never",
  2: "Sometimes",
  3: "Often"
},
"MATHARDSHIP_6":{
  -1: "Refused",
  1: "Never",
  2: "Sometimes",
  3: "Often"
},
"REJECTED_1":{
  -1: "Refused",
  0: "No",
  1: "Yes"
},
"ABSORBSHOCK":{
  -1: "Refused",
  1: "I am certain I could not come up with $2,000",
  2: "I could probably not come up with $2,000",
  3: "I could probably come up with $2,000",
  4: "I am certain I could come up with the full $2,000",
  8: "I dont know"
},
"SHOCKS_1":{
  0: "No",
  1: "Yes"
},
"SHOCKS_3":{
  0: "No",
  1: "Yes"
},
"HEALTH":{
  -1: "Refused",
  1: "Poor",
  2: "Fair",
  3: "Good",
  4: "Very good",
  5: "Excellent"
},
"agecat":{
  1: "18-24",
  2: "25-34",
  3: "35-44",
  4: "45-54",
  5: "55-61",
  6: "62-69",
  7: "70-74",
  8: "75+"
},
"generation":{
  1: "Pre-Boomer",
  2: "Boomer",
  3: "Gen X",
  4: "Millennial"
},
"PPEDUC":{
  1: "Less than high school",
  2: "High school degree/GED",
  3: "Some college/Associate",
  4: "Bachelors degree",
  5: "Graduate/professional degree"
},
"PPETHM":{
  1: "White, Non-Hispanic",
  2: "Black, Non-Hispanic",
  3: "Other, Non-Hispanic",
  4: "Hispanic"
},
"PPGENDER":{
  1: "Male",
  2: "Female"
},
"PPHHSIZE":{
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5+"
},
"PPINCIMP":{
  1: "Less than $20,000",
  2: "$20,000 to $29,999",
  3: "$30,000 to $39,999",
  4: "$40,000 to $49,999",
  5: "$50,000 to $59,999",
  6: "$60,000 to $74,999",
  7: "$75,000 to $99,999",
  8: "$100,000 to $149,999",
  9: "$150,000 or more"
},
"PPMARIT":{
  1: "Married",
  2: "Widowed",
  3: "Divorced/Separated",
  4: "Never married",
  5: "Living with partner"
},
"PPMSACAT":{
  0: "Non-Metro",
  1: "Metro"
}})

In [13]:
ethnicity = df.groupby(["ethnicity", "fwb_score"])
ethnicity.first()

                                                      PUF_ID  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                 10670
                    16                                 13792
                    18                                 13063
                    20                                 13938
                    21                                 10988
...                                                      ...
White, Non-Hispanic 89                                 11508
                    90                                  9463
                    95                                  9922
                    Refused                             7938
                    Response not written to database   12173

                                                                                     sample  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                   General population
                    16                                                   General population
                    18                                                   General population
                    20                                Race/ethnicity and poverty oversample
                    21                                                   General population
...                                                                                     ...
White, Non-Hispanic 89                                                   Age 62+ oversample
                    90                                                   Age 62+ oversample
                    95                                                   Age 62+ oversample
                    Refused                                              General population
                    Response not written to database                     General population

                                                        fed_poverty  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                    <100% FPL
                    16                                    <100% FPL
                    18                                    200%+ FPL
                    20                                    <100% FPL
                    21                                    <100% FPL
...                                                             ...
White, Non-Hispanic 89                                100%-199% FPL
                    90                                    200%+ FPL
                    95                                    200%+ FPL
                    Refused                               200%+ FPL
                    Response not written to database      200%+ FPL

                                                                   fwb1_handle_expense  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                      Not at all
                    16                                                      Not at all
                    18                                                      Not at all
                    20                                                         Refused
                    21                                                      Not at all
...                                                                                ...
White, Non-Hispanic 89                                                      Completely
                    90                                                      Completely
                    95                                                      Completely
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                                    fwb2_secure_future  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                      Not at all
                    16                                                     Very little
                    18                                                        Somewhat
                    20                                                         Refused
                    21                                                      Not at all
...                                                                                ...
White, Non-Hispanic 89                                                       Very well
                    90                                                      Completely
                    95                                                      Completely
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                                    fwb3_things_i_want  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                      Completely
                    16                                                      Completely
                    18                                                      Completely
                    20                                                      Completely
                    21                                                      Completely
...                                                                                ...
White, Non-Hispanic 89                                                      Not at all
                    90                                                      Not at all
                    95                                                      Not at all
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                                       fwb4_enjoy_life  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                      Not at all
                    16                                                      Not at all
                    18                                                     Very little
                    20                                                         Refused
                    21                                                      Not at all
...                                                                                ...
White, Non-Hispanic 89                                                      Completely
                    90                                                       Very well
                    95                                                      Completely
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                                  fwb5_just_getting_by  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                      Completely
                    16                                                      Completely
                    18                                                      Completely
                    20                                                      Completely
                    21                                                      Not at all
...                                                                                ...
White, Non-Hispanic 89                                                      Not at all
                    90                                                      Not at all
                    95                                                      Not at all
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                                  fwb6_worried_savings  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                      Completely
                    16                                                      Completely
                    18                                                      Completely
                    20                                                      Completely
                    21                                                      Completely
...                                                                                ...
White, Non-Hispanic 89                                                      Not at all
                    90                                                      Not at all
                    95                                                      Not at all
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                                    fwb2_1_gift_strain  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                                          Always
                    16                                                          Always
                    18                                                          Always
                    20                                                         Refused
                    21                                                          Always
...                                                                                ...
White, Non-Hispanic 89                                                           Never
                    90                                                           Never
                    95                                                           Never
                    Refused                                                    Refused
                    Response not written to database  Response not written to database

                                                      ...     health  \
ethnicity           fwb_score                         ...
Black, Non-Hispanic 14                                ...       Fair
                    16                                ...       Fair
                    18                                ...       Good
                    20                                ...       Fair
                    21                                ...       Good
...                                                   ...        ...
White, Non-Hispanic 89                                ...  Excellent
                    90                                ...  Very good
                    95                                ...  Very good
                    Refused                           ...       Fair
                    Response not written to database  ...       Good

                                                     age_category  generation  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                      45-54       Gen X
                    16                                      45-54       Gen X
                    18                                      35-44       Gen X
                    20                                      55-61      Boomer
                    21                                      25-34  Millennial
...                                                           ...         ...
White, Non-Hispanic 89                                        75+  Pre-Boomer
                    90                                      70-74      Boomer
                    95                                      70-74      Boomer
                    Refused                                 25-34  Millennial
                    Response not written to database        55-61      Boomer

                                                                         education  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                       Less than high school
                    16                                      High school degree/GED
                    18                                Graduate/professional degree
                    20                                       Less than high school
                    21                                      Some college/Associate
...                                                                            ...
White, Non-Hispanic 89                                            Bachelors degree
                    90                                            Bachelors degree
                    95                                            Bachelors degree
                    Refused                                 High school degree/GED
                    Response not written to database        Some college/Associate

                                                      gender household_size  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                  Male             5+
                    16                                Female              2
                    18                                Female              4
                    20                                Female              2
                    21                                Female             5+
...                                                      ...            ...
White, Non-Hispanic 89                                Female              2
                    90                                  Male              2
                    95                                  Male              2
                    Refused                           Female              2
                    Response not written to database  Female              1

                                                          household_income  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                   Less than $20,000
                    16                                   Less than $20,000
                    18                                  $60,000 to $74,999
                    20                                   Less than $20,000
                    21                                  $30,000 to $39,999
...                                                                    ...
White, Non-Hispanic 89                                  $20,000 to $29,999
                    90                                    $150,000 or more
                    95                                  $75,000 to $99,999
                    Refused                               $150,000 or more
                    Response not written to database  $100,000 to $149,999

                                                           marital_status  \
ethnicity           fwb_score
Black, Non-Hispanic 14                                 Divorced/Separated
                    16                                Living with partner
                    18                                            Married
                    20                                 Divorced/Separated
                    21                                            Married
...                                                                   ...
White, Non-Hispanic 89                                            Widowed
                    90                                            Married
                    95                                            Widowed
                    Refused                                 Never married
                    Response not written to database   Divorced/Separated

                                                     MSA_status final_weight
ethnicity           fwb_score
Black, Non-Hispanic 14                                    Metro     1.609758
                    16                                    Metro     1.151468
                    18                                    Metro     1.140435
                    20                                Non-Metro     1.381361
                    21                                    Metro     0.939962
...                                                         ...          ...
White, Non-Hispanic 89                                Non-Metro     0.963932
                    90                                    Metro     0.721776
                    95                                    Metro     0.487089
                    Refused                               Metro     2.251537
                    Response not written to database      Metro     1.253964

[284 rows x 45 columns]

In [25]:
#Maybe drop strings?
# ethnicity.drop(ethnicity[ethnicity['fwb_score'].map(len) > 3])
#drop all other columns
ethnicity_dropped = ethnicity[['ethnicity','fwb_score']]
ethnicity_dropped.head()

                ethnicity fwb_score
0     White, Non-Hispanic        55
1     White, Non-Hispanic        51
2     Black, Non-Hispanic        49
3     White, Non-Hispanic        49
4     Other, Non-Hispanic        49
...                   ...       ...
6363             Hispanic        24
6365  Black, Non-Hispanic        86
6370  Black, Non-Hispanic        76
6374             Hispanic        30
6378             Hispanic        28

[1185 rows x 2 columns]

In [26]:
ethnicity_dropped.to_csv(r'\ethnicity_fwb_score.csv')

AttributeError: Cannot access callable attribute 'to_csv' of 'DataFrameGroupBy' objects, try using the 'apply' method